USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS SUPPLYGRAPH_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS SUPPLYGRAPH;

CREATE SCHEMA IF NOT EXISTS SUPPLYGRAPH.RAW;
CREATE SCHEMA IF NOT EXISTS SUPPLYGRAPH.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS SUPPLYGRAPH.GOVERNANCE;

USE WAREHOUSE SUPPLYGRAPH_WH;
USE DATABASE SUPPLYGRAPH;
USE SCHEMA RAW;

SELECT
  CURRENT_ROLE(),
  CURRENT_WAREHOUSE(),
  CURRENT_DATABASE(),
  CURRENT_SCHEMA();