USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SUPPLYGRAPH_APP
  COMMENT = 'Read-only runtime role for the SupplyGraph AI application';

GRANT USAGE ON WAREHOUSE SUPPLYGRAPH_WH TO ROLE SUPPLYGRAPH_APP;
GRANT USAGE ON DATABASE SUPPLYGRAPH TO ROLE SUPPLYGRAPH_APP;
GRANT USAGE ON SCHEMA SUPPLYGRAPH.GOVERNANCE TO ROLE SUPPLYGRAPH_APP;

GRANT SELECT ON ALL TABLES IN SCHEMA SUPPLYGRAPH.GOVERNANCE
  TO ROLE SUPPLYGRAPH_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA SUPPLYGRAPH.GOVERNANCE
  TO ROLE SUPPLYGRAPH_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SUPPLYGRAPH.GOVERNANCE
  TO ROLE SUPPLYGRAPH_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SUPPLYGRAPH.GOVERNANCE
  TO ROLE SUPPLYGRAPH_APP;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE SUPPLYGRAPH_APP;

SET APP_USER = CURRENT_USER();
GRANT ROLE SUPPLYGRAPH_APP TO USER IDENTIFIER($APP_USER);

USE ROLE SUPPLYGRAPH_APP;
USE WAREHOUSE SUPPLYGRAPH_WH;
USE DATABASE SUPPLYGRAPH;
USE SCHEMA GOVERNANCE;

SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();